# Generated by Django 4.0.5 on 2022-06-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_paquete_remove_analisis_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
